### ISSUE TITLE
dotnet config not templated

### ISSUE THREAD

**Issue by nwesoccer** [djoos-cookbooks/newrelic#153]
Seems like all of the agents template out the config file, except for the dotnet one.  So when I set the app_name, it doesn't actually take.

**Comment by djoos** [comment]
Hi @nwesoccer,

I'm actually not too familiar with the dotnet installation, but you're right: the actual .NET Agent-config file is not written by this cookbook.

[.NET Agent configuration](https://docs.newrelic.com/docs/agents/net-agent/installation-configuration/net-agent-configuration)

```
<application>
  <name>My App</name>
</application>
```
If you feel like sending over a PR, I'm happy to get this merged in ASAP!

Kind regards,
David

**Comment by nwesoccer** [comment]
@djoos Sounds good.  I'm fairly new to Chef, but I'll whip something up tonight and get a pull request in.  I'd just ask that you go over the pull request intently to ensure I won't mess up anyone's day.  Thanks!

**Comment by DarrellMozingo** [comment]
Another option is setting the app name from your web/app.config file via:

`<add key="NewRelic.AppName" value="My App" />`

**Comment by jvogt** [comment]
I submitted a PR that covers this issue, #262 

Would love to get some feedback / see it merged.

**Comment by djoos** [comment]
@jvogt's PR got merged and shipped in 2.24.0!
