### ISSUE TITLE
.NET agent remote package problems

### ISSUE THREAD

**Issue by minkaotic** [djoos-cookbooks/newrelic#161]
Using Chef 12 on Windows 2008 R2, `windows_package` doesn't really support remote files and tries to install locally (ie a source of `https://somefile` tries to install from `C:\\https:\\somefile` and fails). This issue claims it's just Windows 2008 R2 related, but a follow up to it claims `windows_package` shouldn't officially support remote files anyway:

http://lists.opscode.com/sympa/arc/chef/2014-05/msg00328.html

As with issue #155, we need to either take a dependency on the old `windows` cookbook in metadata, or split the `windows_package` out to a `remote_file` for download and `windows_package` for installation.

For reference, here's the `windows_package` that tries to run as-is for us:

```
windows_package("Install New Relic .NET Agent") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  options "/qb NR_LICENSE_KEY= INSTALLLEVEL=1"
  package_name "Install New Relic .NET Agent"
  source "F:\\http:\\download.newrelic.com\\dot_net_agent\\release\\x64"
  timeout 600
  returns [0]
  declared_type :windows_package
  cookbook_name :newrelic
  recipe_name "dotnet_agent"
end
```

**Comment by DarrellMozingo** [comment]
Any idea how we can move forward fixing this issue?

**Comment by michaelokarimia** [comment]
This would be a great feature to have.

**Comment by djoos** [comment]
Hi guys,

I would give preference to the solution of splitting the windows_package out to a remote_file for download and windows_package for installation, as suggested by @minkaotic above. Would any of you be able to submit a PR to get this fixed?

Thanks in advance!

Kind regards,
David

**Comment by akemner** [comment]
what chef client version are you using? i've been able to do this with chef-client 12.5.x+
