### ISSUE TITLE
PHP 7.0 Support

### ISSUE THREAD

**Issue by bassrock** [djoos-cookbooks/newrelic#230]
So i know the NewRelic doesn't officially support PHP 7.0 yet but 1 change that will need to occur is the php5enmod command. With php 7.0 it has changed to phpenmod. 

The same goes for the php directory. It has also dropped the 5 in favor of just php. 

One way this could be fixed is letting users specify the phpenmod command to run. Currently it is a bool to run the command but it could be changed to a string that can be nil. So if a user needs to run phpenmod they would just need to specify the command instead of nil.

**Comment by djoos** [comment]
Hi @bassrock,

what about perhaps checking the installed version of PHP and use that do drive the command's value?

Thanks in advance!

Kind regards,
David

**Comment by mool** [comment]
I made this PR for add PHP 7.0 support https://github.com/djoos-cookbooks/newrelic/pull/268
