### ISSUE TITLE
python cookbook is deprecated, move to poise-pyton

### ISSUE THREAD

**Issue by growak** [djoos-cookbooks/newrelic#248]

**Comment by biinari** [comment]
This would change the chef requirement to 12.1+ (which is a common requirement among cookbooks now). I expect this would be ok, especially as anyone still needing Chef < 12 can use old version of this cookbook.

I'm working on a PR for this, should be ready later today.

**Comment by djoos** [comment]
See PR #296.

**Comment by jensihnow** [comment]
Looks like the PR is merged (see v2.27.0) and this issue can be closed?
