### ISSUE TITLE
`newrelic_agent_php` LWRP - error on `api_key` parameneter

### ISSUE THREAD

**Issue by thelostspore** [djoos-cookbooks/newrelic#255]
In the [documentation for the latest version](https://supermarket.chef.io/cookbooks/newrelic/versions/2.20.0), there is a parameter for `api_key` for the `newrelic_agent_php` lwrp. During a chef run I noticed this error:

```
ERRORL undefined method `api_key` for LWRP resource `newrelic_agent_php` from cookbook newrelic
```

I do not think an api_key is required to configure the New Relic agent.

**Comment by djoos** [comment]
Hi @thelostspore,

that is definitely an error in the doc as there's no api_key attribute on the agent_php LWRP...

Thanks for spotting that!
David

**Comment by djoos** [comment]
Fixed in master (will go out in an upcoming release)
