### ISSUE TITLE
Stuck on APT 2 cookbook

### ISSUE THREAD

**Issue by jcputter** [djoos-cookbooks/newrelic#258]
I get dependencies issues when wanting to use apt 4.0 cookbook?

**Comment by djoos** [comment]
Hi @jcputter,

yeah, apt is currently [pinned in metadata.rb](https://github.com/djoos-cookbooks/newrelic/blob/master/metadata.rb#L18).

I don't think there's any reason why we need to keep that pin - so, happy for you to send a PR if you want to speed things up...

Hope this helps!
David

**Comment by mike-stewart** [comment]
+1

I tried the fix in #259 and it works for me.

**Comment by djoos** [comment]
FYI: fixed in PR #259, thanks @jcputter!
