### ISSUE TITLE
Problems Trying to Setup Newrelic with Chef 11.10 in AWS Opsworks

### ISSUE THREAD

**Issue by caffe** [djoos-cookbooks/newrelic#260]
Hello,

I'm following this tutorial from AWS in order to setup Newrelic monitoring (PHP App) in my Opsworks environment using Chef 11.10.

http://blogs.aws.amazon.com/application-management/post/Tx1T7B0Y37JQER9/Using-New-Relic-to-monitor-applications-on-AWS-OpsWorks

The current version of this cookbook is not compatible with Chef 11.10 anymore only Chef 12. The tutorial mentions cookbook version 1.0.6 as being the one to be used.

However, I'm getting the following error:

`ERROR: undefined method 'property_type' for MysqlCookbook::MysqlBase:Class`

I posted a question on the tutorial and the AWS guy gave me the following answer:

> I'm not sure how you can fix that on your end. My guess is that somewhere in the dependency tree one of the cookbooks does not have all its dependencies pinned to exact versions, and a result you end up with a mix of old an new versions of cookbooks that have never been tested together. One thing worth trying is to figure out what the dependency closure looks like, and then use your Berksfile to pin every cookbook to the latest version you can find, assuming the dependency constraints in the cookbooks involved give you that freedom. I'm sorry I can't give you a better answer, but that's how I would drill into this issue.

His suggestion seems impossible for me since I only have basic knowledge in this field.

I also considered building a Stack with Chef 12 but AWS doesn't allow built-in recipes to setup the environment when you use Chef 12 Stack which makes it even harder for me to work with.

Can you somehow help me with this issue? I would very much appreciate it.

Thanks,
Walter

**Comment by djoos** [comment]
Hi Walter,

could you let me know which version of the mysql cookbook you are running? It seems to be an issue with that cookbook's version.

Any chance you could pin that cookbook to a lower version? I had a quick look and it's only from 8.0.0 that Chef 12 is required. Perhaps give 7.2.0 a go?

Hope this helps, please do keep me updated!

Kind regards,
David

**Comment by caffe** [comment]
Hi David,

Thank you for your reply.

I have just realized I made a mistake. This problem was happing with another repository (https://github.com/escapestudios-cookbooks/newrelic.git). Sorry.

From what version does your cookbook require Chef 12? In other words, what's the best version to be used with Chef 11.10?

Thanks,
Walter

**Comment by caffe** [comment]
David,

So, you know, I'm just using newrelic::default and newrelic::php_agent

Thanks,
Walter

**Comment by caffe** [comment]
David,

It worked with version 2.0.0!! :)

If there is a newer version still compatible with Chef 11, please, let me know.

All the best,
Walter

**Comment by estedev** [comment]
Hi Walter,

I'm glad you got it working with 2.0.0 (I wouldn't recommend using 1.x of the cookbook anymore!)
Would you mind giving it a go with the latest version of the cookbook, 2.22.3?

Thanks in advance for your feedback!
David

**Comment by caffe** [comment]
Hi David,

Sure. I have just tested it and got the following error from Opsworks.

If you need me to make additional tests, please, let me know.

Best regards,
Walter

================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb
================================================================================
 
 
RuntimeError
------------
This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb:2:in `<top (required)>'
 
 
Relevant File Content:
----------------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb:
 
1:  unless Gem::Requirement.new(">= 12.0").satisfied_by?(Gem::Version.new(Chef::VERSION))
2>>   raise "This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade."
3:  end
4:  
5:  # If the gem is already activated rather than the cookbook, then we fail if our version is DIFFERENT.
6:  # The user said they wanted this cookbook version, they need to have this cookbook version.
7:  # NOTE: if the gem is installed but on a different version, we simply don't care: the cookbook version wins.
8:  #       If another gem depends on a different version being there, rubygems will correctly throw the error.
9:  if Gem.loaded_specs["compat_resource"]
10:    # Read our current version
11:    version_rb = IO.read(File.expand_path("../../files/lib/compat_resource/version.rb", __FILE__))
 
 
 
[2016-08-23T20:36:50+00:00] ERROR: Running exception handlers
[2016-08-23T20:36:50+00:00] ERROR: Exception handlers complete
[2016-08-23T20:36:50+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2016-08-23T20:36:50+00:00] ERROR: This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
[2016-08-23T20:36:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by djoos** [comment]
Hi Walter,

ah yes, I forgot about the 12.5 custom resources... Unfortunately you'll have to run with an older version of the cookbook - however, I do hope OpsWorks finally gets past Chef 11 as a lot of stuff moved on :-)

I'll close this issue for now, however: let me know if you have any further questions or comments though!

Kind regards,
David

**Comment by caffe** [comment]
Hi David,

No worries. Actually Opsworks already offers Chef 12 but not with the built-in recipes which are crucial for me. I hope they can soon upgrade my type of stack with Chef 12.

Kind regards,
Walter
