### ISSUE TITLE
Proper way to set service_actions for the server_monitor

### ISSUE THREAD

**Issue by nukepuppy** [djoos-cookbooks/newrelic#269]
i saw the default in https://github.com/djoos-cookbooks/newrelic/blob/master/resources/server_monitor.rb#L28

however after trying to set this in an environment value.. the values are ignored?
whats the proper syntax in non %w() format to set the service actions to just 'enable' ? and not start.. think of systems with packer or something where you're just baking images and not running them yet

**Comment by djoos** [comment]
Hi @nukepuppy,

I spotted the info on Slack provided by Szymon - let me know if you're up and running or having any issues, if perhaps we can close the issue?

Thanks!

**Comment by nukepuppy** [comment]
Heya @djoos  thanks for looking into it.. i think i'm set with the override section!
