### ISSUE TITLE
Cannot Assign Linux Server to Policy

### ISSUE THREAD

**Issue by BenLiyanage** [djoos-cookbooks/newrelic#273]
Hey,

When trying to assign a server policy I get an error.

My recipe looks roughly like this:

```
newrelic_server_monitor 'Install' do
  license "the license"
  hostname "my-host"
end
```

I get the following error.

```
* ruby_block[Move server to newrelic decommissioned policy] action run

================================================================================
Error executing action `run` on resource 'ruby_block[Move server to newrelic decommissioned policy]'
================================================================================

NoMethodError
-------------
undefined method `empty?' for Chef::Resource::RubyBlock

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/newrelic/providers/server_monitor.rb:101:in `block (2 levels) in update_newrelic_alert_policy_linux'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/newrelic/providers/server_monitor.rb

95:   ruby_block 'Move server to newrelic decommissioned policy' do
96:     block do
97:       update_alert_policy(alert_policy_id)
98:     end
99:
100:     only_if do
101:       node['newrelic']['api_key'].!empty?
102:     end
103:   end
104: end

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/newrelic/providers/server_monitor.rb:95:in `update_newrelic_alert_policy_linux'
```

To fix this I have tried setting node['newrelic']['api_key'] like this :
- In the recipe: `node.default['newrelic']['api_key']='the key'`
- In my cookbooks `attributes/defaults.rb` like this: `default['newrelic']['api_key'] = 'the key'`

What is the correct way to set the api key?  Is `.empty?` not legit in the recipe here? I can post the PR if that is the case. (I have relatively minor chef experience, but can probably get around the test suite).

**Comment by BenLiyanage** [comment]
Quick update:  I have also tried setting the api key with `override` and `force_override`.  Currently I'm working around this defect with the following snippet in my recipe:

```
node.default["newrelic"]["api_key"] = 'thekey'
Chef::Recipe.send(:include, NewRelic::ServerMonitorHelpers)
update_alert_policy('thepolicyid')
```

There also appears to be a bug in the function update_alert_policy where it is using the hostname that the os returns, as opposed to the host name in the config file (if you specify a different default).

That bug can be seen here:
https://github.com/djoos-cookbooks/newrelic/blob/ca78b0ccee1e5ff1af5d02f88749603008126f61/libraries/server_monitor_helpers.rb#L20-L21

**Comment by djoos** [comment]
Hi Ben,

re: "undefined method `empty?' for Chef::Resource::RubyBlock"
Could you give 2.22.4 a go? A [bugfix](https://github.com/djoos-cookbooks/newrelic/commit/ca78b0ccee1e5ff1af5d02f88749603008126f61) for the server_monitor.rb-recipe was pushed out in that version yesterday...

re: setting the api_key
How do you currently set your attributes?
node.default['newrelic']['api_key']='the key' in a wrapper cookbook prior to the inclusion of the server_monitor-recipe should do the trick...

Thanks in advance for your feedback!
David

**Comment by BenLiyanage** [comment]
I'm setting my node like this:
`node.default["newrelic"]["api_key"] = 'thekey'`

2.22.4 and 2.23.0 (saw this version this morning as well) works like a charm.

What do you want to do about the host name bug?  I'm looking to get around this by setting the host name of my machine, but it'd be nice if this cookbook was internally consistent as well.

**Comment by BenLiyanage** [comment]
BTW thanks for responding so quickly!  I really appreciate it.

**Comment by djoos** [comment]
Hi Ben,

would you mind detailing the hostname bug a bit more?

Thanks in advance, have a great evening!

**Comment by BenLiyanage** [comment]
Lets say my computers hostname is some auto-generated garbage in a cloud system like `asdf`.  If I know I want my host to be reported to new relic as `my-app`, and be assigned to alert_policy_id 12345.   I build my newrelic resource like this:

```
newrelic_server_monitor 'Install' do
  license "the license"
  hostname "my-app"
  alert_policy_id "12345"
end
```

When the code that goes to assign the policy to the host runs, it gets the hostname `asdf` not `my-app` here:

https://github.com/djoos-cookbooks/newrelic/blob/ca78b0ccee1e5ff1af5d02f88749603008126f61/libraries/server_monitor_helpers.rb#L20-L21

As a result the code searches for an app named `asdf` and does not find it.

**Comment by djoos** [comment]
A ok, got it - thanks for clarifying that!

Would you mind giving the temp [feature/hostname-branch](https://github.com/djoos-cookbooks/newrelic/tree/feature/hostname) a spin?

Thanks in advance for your feedback!

**Comment by djoos** [comment]
The temp branch got merged into master. I'll close this issue for now, but please give me a shout when you get the time to give the new version a spin!

Kind regards,
David
