### ISSUE TITLE
Latest version (2.23.1) can't download newrelic agent zip if version is set

### ISSUE THREAD

**Issue by petergphillips** [djoos-cookbooks/newrelic#275]
Latest version contains the line
```
 https_download = "https://download.newrelic.com/newrelic/java-agent/newrelic-agent/#{version}/newrelic-java.zip"
```
That zip file only exists if version set to current, for all others the zip file contains the version number i.e. https://download.newrelic.com/newrelic/java-agent/newrelic-agent/3.32.0/newrelic-java-3.32.0.zip

**Comment by djoos** [comment]
Well spotted - we should have picked that up as well. On the other hand a bit of consistency on New Relic's end would have been helpful ;-)
