### ISSUE TITLE
recepie for installing agent-sdk

### ISSUE THREAD

**Issue by pankajv82** [djoos-cookbooks/newrelic#282]
Hi, 
Can you please point me to recepie to install SDK. I have CentOS 7 box and running chef. I want to install SDK using chef. 
https://docs.newrelic.com/docs/agents/agent-sdk

**Comment by djoos** [comment]
Hi @pankajv82,

unfortunately there's no support yet for the Agent SDK in the cookbook. The New Relic agent SDK is currently in beta, but I do hope to get it implemented in the future - I've opened #283 to track it.

PRs to speed up implementation of the Agent SDK are always welcome...

Have a great day!
David

**Comment by pankajv82** [comment]
@djoos Thanks.

**Comment by djoos** [comment]
Let's use #283 going forward - closing this particular issue!
