### ISSUE TITLE
Unable to configure class_transformer in newrelic.yml (Java agent)

### ISSUE THREAD

**Issue by Tom-Van-Asch** [djoos-cookbooks/newrelic#287]
Hello

I'm not able to configure class_transformer via the cookbook in the newrelic.yml file as decribed here: 
https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-config-file-template

In my case I would like to configure the following lines via chef:

class_transformer:
    quartz_system:
      enabled: false
    quartz_job:
      enabled: false

Can this be added to the current cookbook?

Kind regards

Tom

**Comment by djoos** [comment]
Referencing PR #281.

**Comment by djoos** [comment]
PR #281 just got merged in and will get released shortly!
