### ISSUE TITLE
Add support for New Relic Infrastructure Agent

### ISSUE THREAD

**Issue by lhriley** [djoos-cookbooks/newrelic#291]
New Relic Infrastructure is a "new" service from New Relic which appears to be intended to replace the existing New Relic Server monitoring agent which is no longer available to new customers.

It would be great to get a new resource to manage the installation of the New Relic Infrastructure agent. I'm including relevant links to the documentation below.

> New Relic Infrastructure provides full-featured, near real-time host monitoring for Linux and Windows. 
>
> You can run both New Relic Infrastructure and New Relic Servers on the same host without issues. For an index of all Infrastructure documentation, see New Relic Infrastructure.
>
> New Relic Servers is available for existing users, but not for New Relic accounts created after November 16, 2016. If a master account has access to Servers, any new sub-accounts created after November 16, 2016 will also have Servers access.

Thanks!

More information: 
- https://docs.newrelic.com/docs/servers/servers-pages/servers-ui/new-relic-servers-new-relic-infrastructure
- https://docs.newrelic.com/docs/servers/new-relic-servers-linux
- https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/install-infrastructure-linux

**Comment by growak** [comment]
Hello djoos,

Here is a basic recipe provided by New Relic.

https://github.com/newrelic/infrastructure-agent-chef

Fred

**Comment by djoos** [comment]
Thanks!

FYI: I've just created a feature branch (feature/infrastructure) that heavily relies on the newrelic/infrastructure-agent-chef cookbook.

It's not polished up yet, nor fully tested - but I've pushed the WIP version up and would just like highlight here that getting this tested and merged into master is one of my priorities...

To be continued!

**Comment by djoos** [comment]
The initial implementation of the New Relic Infrastructure agent went out in v2.29.0, I'll close this issue!
