### ISSUE TITLE
unable to set application name

### ISSUE THREAD

**Issue by MartinAmmerlaanValtech** [djoos-cookbooks/newrelic#294]
Hello,

I am trying to install the dotnet_agent for multiple nodes, some have different appname's. Two nodes have 'customername-frontend-production', two have 'customername-frontend-acceptance' and 'customername-frontend-test' and so on.

I have set the appname in the node attributes to be picked up. But these params are not pushed to the newrelic.config, it defaults back to 'My Application'

Any idea's who to handle this?

Node attributes
{
  "tags": [],
  "newrelic": {
    "license": "mysupersecretlicensekey",
    "dotnet_agent": {
      "app_name": "customername-frontend-production"
    }
  }
}

C:\ProgramData\New Relic\.NET Agent\newrelic.config
....
  <application disableSamplers="false">
    <name>My Application</name>
  </application>
....

**Comment by djoos** [comment]
Hi @MartinAmmerlaanValtech,

thanks for reaching out!

Currently, the [dotnet_agent.rb-recipe](https://github.com/djoos-cookbooks/newrelic/blob/master/recipes/dotnet_agent.rb) does not pass on the dotnet_agent's app_name-attribute to the LRWP. The other recipes do set (the majority of LWRP attributes), but not the dotnet one (yet).

I'll make a note of this to get this sorted in an upcoming release, however I'd advise to create a [wrapper cookbook](https://blog.chef.io/2013/12/03/doing-wrapper-cookbooks-right/), eg. acme-newrelic, and use the LWRP there directly with the desired attributes:
```
newrelic_agent_dotnet 'Install' do
  license 'xyz'
  app_name 'My Application'
end
```

Hope this helps!

Kind regards,
David

**Comment by djoos** [comment]
Hi @MartinAmmerlaanValtech,

did the wrapper cookbook solution work for you?

Thanks in advance for your feedback!
David

**Comment by MartinAmmerlaanValtech** [comment]
Hi Djoos,

Yes the wrapper worked.
I needed some help on that, since I am do not have much experience yet. But we managed to work something out.

Kind regards,
Martin

**Comment by djoos** [comment]
Thanks for your feedback @MartinAmmerlaanValtech - next time round don't hesitate to give me a shout if you need some help!
