### ISSUE TITLE
java agent cookbook issue

### ISSUE THREAD

**Issue by ryanmkaplan** [djoos-cookbooks/newrelic#303]
Has anyone else seen this issue? It just keeps looping...

`Current  directory[.]: /var/chef/cache/cookbooks/newrelic/providers/agent_java.rb:94:in `allow_app_group_write_to_log_file_path' (CHEF-3694)/var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/resource_cloning.rb:58:in `emit_cloned_resource_warning'.
Please see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/event_dispatch/dispatcher.rb:43:in `call'`

**Comment by djoos** [comment]
Hi @ryanmkaplan, we haven't had this flagged before - the issue seems to originate in the [poise](https://github.com/poise/poise) cookbook...

**Comment by djoos** [comment]
(closed due to fact this issue originates in the poise-cookbook)
