### ISSUE TITLE
Support HTTPS when downloading windows MSI

### ISSUE THREAD

**Issue by jwitrick** [djoos-cookbooks/newrelic#308]
The client I work for has strict policies limiting the use of http. One workaround is to change the source url to be 'https'.

Another workaround is to have the URL be an input (where the default version is specified in the attributes file instead of resources file).

Specifically I am talking about the server_monitor resource, but there might be others.

**Comment by djoos** [comment]
Hi @jwitrick,

this was not addressed in the server monitor install, but will be fixed in 2.31.1!

Hope this helps!
