### ISSUE TITLE
Chef 12.1 or newer is required

### ISSUE THREAD

**Issue by miguelb** [djoos-cookbooks/newrelic#310]
Currently the readme states:
```Make sure you run Chef >= 0.10.0.```

However, since this cookbook is now dependent ```poise-python```, this no longer seems to be the case. We are running chef 11.x and unable to get the latest version (```2.30.0```) running. The highest version we are able to install seems to be version ```2.26.0```.

Miguel

**Comment by djoos** [comment]
Fixed in 2.31.0, hope this helps!
David
