### ISSUE TITLE
'sudo java -jar newrelic.jar -s /opt/newrelic/java install' is failing

### ISSUE THREAD

**Issue by practiseemail** [djoos-cookbooks/newrelic#312]
<img width="897" alt="screen shot 2017-10-10 at 3 30 18 pm" src="https://user-images.githubusercontent.com/28658667/31413801-f8cc8224-adcf-11e7-8130-fb386fdc32c8.png">
Tomcat is running on the server. Still I am getting the same error?

**Comment by djoos** [comment]
Hi @practiseemail,

are you setting an install_dir on the agent_java LWRP with the location of your Tomcat install?
(FYI: if not, the cookbook assumes it's /opt/newrelic/java)

Thanks in advance for your feedback!
David

**Comment by djoos** [comment]
* nudge *

FYI: I'll close this for now, but happy to reopen upon further information...
