### ISSUE TITLE
newrelic.config.erb issue with proxy child of service element closure tag in wrong place

### ISSUE THREAD

**Issue by bcorner13** [djoos-cookbooks/newrelic#321]
"The proxy element is an optional child of the service element. Use the proxy element if you want the agent to communicate with New Relic service via a proxy." from newrelic doco

Currently the closure tag for the service element is on line 15.  it really needs to be after the proxy element, around line 31.  Otherwise the proxy element ends up being a child of configuration instead of service.

**Comment by djoos** [comment]
Fixed in #322
