### ISSUE TITLE
404 "Not Found"

### ISSUE THREAD

**Issue by mmclane** [djoos-cookbooks/newrelic#328]
As of last Friday (Feb. 2nd 2018) the newrelic cookbook started failing. We get the following error.
[2018-02-05T09:55:24-05:00] WARN: remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\package\x64] cannot be downloaded from https://download.newrelic.com/dot_net_agent/release/x64: 404 "Not Found"

================================================================================
    Error executing action `create` on resource 'remote_file[C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cache\package\x64]'
    ================================================================================

    Net::HTTPServerException
    ------------------------
    404 "Not Found"

I have confirmed that there isn't anything at https://download.newrelic.com/dot_net_agent/release/x64

I have tried to set default['newrelic']['dotnet_agent']['https_download'] = 'https://download.newrelic.com/dot_net_agent/latest_release/NewRelicDotNetAgent_x64.msi' where I found an installer, but it doesn't change where it is trying to download from.

**Comment by mmclane** [comment]
* windows_package[Install New Relic .NET Agent] action install[2018-02-05T10:07:57-05:00] INFO: Processing windows_package[Install New Relic .NET Agent] action install (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/newrelic/providers/agent_dotnet.rb line 23)

**Comment by fdzedzy** [comment]
@mmclane I had the same issue.  If you look at the agent_dotnet resource, it has an https_download attribute that is not set to the default attribute.  So it doesn't appear that the default attribute is even used.  You have to pass the new URL in to the resource like this:
```
newrelic_agent_dotnet 'Install' do
  https_download 'https://download.newrelic.com/dot_net_agent/latest_release/NewRelicDotNetAgent_x64.msi'
  license '0000ffff0000ffff0000ffff0000ffff0000ffff'
end
```

**Comment by djoos** [comment]
Hi,

when using the recipe, the https_download attribute is [not set as an attribute on the resource](https://github.com/djoos-cookbooks/newrelic/blob/master/recipes/dotnet_agent.rb#L8-L10).

I'd recommend using the resource directly as the plan is that in a future release the recipes will be phased out...

Hope this helps!
David

**Comment by djoos** [comment]
In the meantime: the [resource default for https_download](https://github.com/djoos-cookbooks/newrelic/blob/master/resources/agent_dotnet.rb#L11) will need to get updated to 'https://download.newrelic.com/dot_net_agent/latest_release/NewRelicDotNetAgent_x64.msi', as New Relic seem to have removed 'https://download.newrelic.com/dot_net_agent/release/x64'.

**Comment by mmclane** [comment]
Looking into this further, we no longer have need to install NewRelic so for us the answer is to remove the installer from our cookbook.  Because of that I am going to close the issue but you really should update the README for the cookbook.  It is inaccurate.
