### ISSUE TITLE
Download Path to DotNet Agent has been changed, causing 404 errors

### ISSUE THREAD

**Issue by scolligan** [djoos-cookbooks/newrelic#329]
Today we began to notice failures when installing the NewRelic DotNet agent on some new servers.  They were reporting a 404 error.

Upon further investigation, the default path for the download is:

`default['newrelic']['dotnet_agent']['https_download'] = 'https://download.newrelic.com/dot_net_agent/release/x64'`

However, that path no longer exists on the download.newrelic.com site:

![image](https://user-images.githubusercontent.com/10987212/35866735-91797ae0-0b1d-11e8-87eb-4df9b6ccb232.png)

Thanks,

Sean

**Comment by djoos** [comment]
Fixed in v2.33.0 - shipped to Chef supermarket.

Thanks in advance for your feedback!

Kind regards,
David

**Comment by scolligan** [comment]
Thanks for the quick fix!  We'll try out the new cookbook.

Also, FWIW, we tried to override the node attribute:

`node.override['newrelic']['dotnet_agent']['https_download'] = 'https://download.newrelic.com/dot_net_agent/latest_release/x64'`

but continued seeing the error.  When we dug a bit deeper, it looks like the node attribute value isn't being used by the resource (not certain)?

```
#
# Cookbook Name:: newrelic
# Resource:: agent_dotnet
#
# Copyright (c) 2016, David Joos
#

actions :install, :remove
default_action :install

attribute :https_download, :kind_of => String, :default => 'https://download.newrelic.com/dot_net_agent/release/x64'
attribute :install_level, :kind_of => String, :default => '1'
```
If you think this is legit, I can create a separate issue for this.

Thanks,

Sean

**Comment by djoos** [comment]
Hi Sean,

you're right - that was flagged in #328: the attribute wasn't passed onto the resource in the dotnet-recipe. This got rectified in v2.33.0 as well.

Hope this helps!
David
