### ISSUE TITLE
Download Path to DotNet Agent has changed again, 404 errors

### ISSUE THREAD

**Issue by kev-in-shu** [djoos-cookbooks/newrelic#346]
Hi,

It seems Newrelic changed their download paths again for the dotnet agent, so unless we explicitly set the https_download attribute, we get 404 errors.

The sad thing is, currently there is no generic url to get the latest version.

![image](https://user-images.githubusercontent.com/7252851/40221739-8ce384bc-5a7d-11e8-867c-85d27b01b308.png)

**Comment by kev-in-shu** [comment]
I just opened a discussion at newrelic community forum to ask about the generic download urls

https://discuss.newrelic.com/t/generic-dotnet-agent-latest-installer-url/55803

**Comment by seikarui** [comment]
When will this download url be fixed in cookbook?

**Comment by Ellmi** [comment]
need fix +1
