### ISSUE TITLE
Infra template marked as sensitive, but file on disk is world readable.

### ISSUE THREAD

**Issue by mynamewastaken** [djoos-cookbooks/newrelic#347]
https://github.com/djoos-cookbooks/newrelic/blob/46fb82d068a19dc1eb8470395902293dbb0c5074/providers/agent_infrastructure.rb#L35-L39

What's the rationale behind this? If it should be `sensitive`, consider changing the file permissions to 600 or something, or else, remove the `sensitive` attribute. I'm happy to make a PR if this isn't intended behavior.

**Comment by djoos** [comment]
Hi there,

sensitive got added to prevent the innards from showing up in Chef client run logs. However, happy for you to send a PR with tighter file permissions.

Thanks in advance!
David
