### ISSUE TITLE
doesn't support strip_command_line parameter

### ISSUE THREAD

**Issue by brunotag** [djoos-cookbooks/newrelic#364]
Hey, so, there's a handy undocumented config parameter for the infrastructure agent.

It's called `strip_command_line` - it defaults to `true`, but setting it to `false` is handy under some circumstances.
See for instance
https://discuss.newrelic.com/t/is-there-a-way-to-differentiate-linux-processes-by-process-arguments/53632

It appears this recipe doesn't implement it.. right? Is that intentional or would you consider supporting it?

**Comment by djoos** [comment]
Hi @brunotag,

thanks for reaching out - that sounds like a very interesting addition; if you've got time to send over a PR, I'll get it merged in ASAP!

Thanks in advance!

**Comment by djoos** [comment]
Fixed by #365
