### ISSUE TITLE
Every node attribute used a default value to a property needs  a `lazy { }` around it.

### ISSUE THREAD

**Issue by lamont-granquist** [djoos-cookbooks/newrelic#368]
related to #345, but every other one of the values needs lazy {} as well, e.g.:

https://github.com/djoos-cookbooks/newrelic/blob/master/resources/yml.rb#L28

(just to pick one).

see for example:

https://github.com/chef/chef/blob/60fe89dcf071ded1249adad59fd1df0c098d7f42/lib/chef/resource/apt_repository.rb#L46

**Comment by fernandoaleman** [comment]
Just ran into this problem as well. Adding `lazy {}` to the default attributes fixes the problem. @djoos Any chance of getting this fixed soon?

**Comment by fernandoaleman** [comment]
@djoos Hello again. Any chance this pull request can be merged in to fix this issue soon? Much appreciated.

**Comment by barrowkwan** [comment]
this broken the unit test.  can this fix merge soon?  thanks

**Comment by fernandoaleman** [comment]
@djoos I see you finally made some updates recently. Any chance of getting this fixed soon?

**Comment by djoos** [comment]
Apologies for the super late merge; this is now shipped in v2.43.0...
Thank you for your patience!

**Comment by fernandoaleman** [comment]
> Apologies for the super late merge; this is now shipped in v2.43.0...
> Thank you for your patience!

Thanks so much @djoos this is very helpful. 👍
