### ISSUE TITLE
[agent_dotnet] Add support for enabling distributed tracing on the newrelic.config.erb template

### ISSUE THREAD

**Issue by scrthq** [djoos-cookbooks/newrelic#379]
This is primarily focused on the `dotnet` agent, but I'm also not seeing this newer functionality in anywhere in the repo, so I'm assuming that it's not supported in this cookbook at all yet. Pics/references will be using the .NET Agent as the example.

What needs to happen:
- Add the following line to the [`newrelic.config.erb` template](https://github.com/djoos-cookbooks/newrelic/blob/master/templates/default/agent/dotnet/newrelic.config.erb) under the main `configuration` element:

```xml
  <distributedTracing enabled="<%= @resource.distributed_tracing_enabled %>" />
```

- Add the additional attribute 'distributed_tracing_enabled' to the [agent_dotnet.rb custom resource](https://github.com/djoos-cookbooks/newrelic/blob/master/resources/agent_dotnet.rb):

```ruby
attribute :distributed_tracing_enabled, :kind_of => [TrueClass, FalseClass], :default => false
```

***

Image showing the config setting from the .NET agent documentation (click the image to view the doc page directly):

[![image](https://user-images.githubusercontent.com/12724445/59947430-db4c5800-9432-11e9-9188-bde4499ef87e.png)](https://docs.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration#distributed_tracing)

***

Pull request with code changes: [Add Distributed Tracing support for the .NET Agent #380](https://github.com/djoos-cookbooks/newrelic/pull/380)

**Comment by djoos** [comment]
Fixed in #380
