### ISSUE TITLE
Default value of 'windows_checksum' in newrelic/resources/agent_infrastructure.rb does not match computed checksum

### ISSUE THREAD

**Issue by nickor** [djoos-cookbooks/newrelic#382]
The SHA256 checksum of newrelic-infra.1.0.703.msi is dd528d84a6d82f9efc41369bbfcb92b6aa504bf20fc2ad23b1693d05efa22a9e instead of 3c9f98325dc484ee8735f01b913803eaef54f06641348b3dd9f3c0b3cd803ace.

Recipe: newrelic::infrastructure_agent
  * newrelic_agent_infrastructure[Install] action install
    * windows_package[newrelic-infra] action install
    Recipe: <Dynamically Defined Resource>
      * remote_file[c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi] action create

        ================================================================================
        Error executing action `create` on resource 'remote_file[c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi]'
        ================================================================================

        Chef::Exceptions::ChecksumMismatch
        ----------------------------------
        Checksum on resource (3c9f98) does not match checksum on content (dd528d)

        Compiled Resource:
        ------------------
        # Declared in

        remote_file("c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi") do
          action [:create]
          default_guard_interpreter :default
          source ["https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.1.0.703.msi"]
          cookbook_name "newrelic"
          checksum "3c9f98325dc484ee8735f01b913803eaef54f06641348b3dd9f3c0b3cd803ace"
          path "c:\\users\\korn\\documents\\repo\\chef-sharding\\local-mode-cache\\cache\\package\\newrelic-infra.1.0.703.msi"
          headers {}
          rights nil
          deny_rights nil
          verifications []
        end

        System Info:
        ------------
        chef_version=15.2.20
        platform=windows
        platform_version=10.0.17134
        ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
        program_name=C:/opscode/chef-workstation/bin/chef-client
        executable=C:/opscode/chef-workstation/bin/chef-client

      ================================================================================
      Error executing action `install` on resource 'windows_package[newrelic-infra]'
      ================================================================================

      Chef::Exceptions::ChecksumMismatch
      ----------------------------------
      remote_file[c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi] (dynamically defined) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (3c9f98) does not match checksum on content (dd528d)

      Resource Declaration:
      ---------------------
      # In c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/providers/agent_infrastructure.rb

       93:   windows_package 'newrelic-infra' do
       94:     source "https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.#{new_resource.windows_version}.msi"
       95:     installer_type :msi
       96:     version new_resource.windows_version
       97:     action new_resource.action
       98:     checksum new_resource.windows_checksum
       99:   end
      100:

      Compiled Resource:
      ------------------
      # Declared in c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/providers/agent_infrastructure.rb:93:in `install_newrelic_infrastructure_service_windows'

      windows_package("newrelic-infra") do
        package_name "newrelic-infra"
        action [:install]
        default_guard_interpreter :default
        declared_type :windows_package
        cookbook_name "newrelic"
        source "https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.1.0.703.msi"
        installer_type :msi
        version "1.0.703"
        checksum "3c9f98325dc484ee8735f01b913803eaef54f06641348b3dd9f3c0b3cd803ace"
      end

      System Info:
      ------------
      chef_version=15.2.20
      platform=windows
      platform_version=10.0.17134
      ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
      program_name=C:/opscode/chef-workstation/bin/chef-client
      executable=C:/opscode/chef-workstation/bin/chef-client

    ================================================================================
    Error executing action `install` on resource 'newrelic_agent_infrastructure[Install]'
    ================================================================================

    Chef::Exceptions::ChecksumMismatch
    ----------------------------------
    windows_package[newrelic-infra] (c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/providers/agent_infrastructure.rb line 93) had an error: Chef::Exceptions::ChecksumMismatch: remote_file[c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi] (dynamically defined) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (3c9f98) does not match checksum on content (dd528d)

    Resource Declaration:
    ---------------------
    # In c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/recipes/infrastructure_agent.rb

      8: newrelic_agent_infrastructure 'Install'

    Compiled Resource:
    ------------------
    # Declared in c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/recipes/infrastructure_agent.rb:8:in `from_file'

    newrelic_agent_infrastructure("Install") do
      action [:install]
      default_guard_interpreter :default
      declared_type :newrelic_agent_infrastructure
      cookbook_name "newrelic"
      recipe_name "infrastructure_agent"
    end

    System Info:
    ------------
    chef_version=15.2.20
    platform=windows
    platform_version=10.0.17134
    ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
    program_name=C:/opscode/chef-workstation/bin/chef-client
    executable=C:/opscode/chef-workstation/bin/chef-client

Running handlers:
[2019-12-16T15:27:01+08:00] ERROR: Running exception handlers
Running handlers complete
[2019-12-16T15:27:01+08:00] ERROR: Exception handlers complete
Chef Infra Client failed. 3 resources updated in 33 seconds
[2019-12-16T15:27:01+08:00] FATAL: Stacktrace dumped to c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/chef-stacktrace.out
[2019-12-16T15:27:01+08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-12-16T15:27:01+08:00] FATAL: Chef::Exceptions::ChecksumMismatch: newrelic_agent_infrastructure[Install] (newrelic::infrastructure_agent line 8) had an error: Chef::Exceptions::ChecksumMismatch: windows_package[newrelic-infra] (c:/users/korn/documents/repo/chef-sharding/local-mode-cache/cache/cookbooks/newrelic/providers/agent_infrastructure.rb line 93) had an error: Chef::Exceptions::ChecksumMismatch: remote_file[c:\users\korn\documents\repo\chef-sharding\local-mode-cache\cache\package\newrelic-infra.1.0.703.msi] (dynamically defined) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (3c9f98) does not match checksum on content (dd528d)

**Comment by djoos** [comment]
#383 fixes #382
